package com.poc.trackernosql;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "error-tracker")
public class Tracker {
	private String messageId;
	private String timestamp;
	private String status;
	private String description;

	public Tracker(String timestamp, String status, String description) {
		this.timestamp = timestamp;
		this.status = status;
		this.description = description;
	}

	public Tracker() {
// Default constructor is required by AWS DynamoDB SDK
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getMessageId() {
		return messageId;
	}

	@DynamoDBAttribute
	public String getStatus() {
		return status;
	}

	@DynamoDBAttribute
	public String getTimestamp() {
		return timestamp;
	}

	@DynamoDBAttribute
	public String getDescription() {
		return description;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		Tracker tracker = (Tracker) o;
		return messageId.equals(tracker.messageId) &&
				timestamp.equals(tracker.timestamp) &&
				status.equals(tracker.status) &&
				description.equals(tracker.description);
	}

	@Override
	public int hashCode() {
		return Objects.hash(messageId, timestamp, status, description);
	}
}
